steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'gcr.io/$PROJECT_ID/oauth-user-inspector:$COMMIT_SHA',
      '-t',
      'gcr.io/$PROJECT_ID/oauth-user-inspector:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/oauth-user-inspector:$COMMIT_SHA'
    ]

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/oauth-user-inspector:latest'
    ]

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      'oauth-user-inspector',
      '--image',
      'gcr.io/$PROJECT_ID/oauth-user-inspector:$COMMIT_SHA',
      '--region',
      'us-west1',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      '--port',
      '8080',
      '--memory',
      '512Mi',
      '--cpu',
      '1000m',
      '--timeout',
      '300s',
      '--max-instances',
      '10',
      '--set-env-vars',
      'NODE_ENV=production'
    ]

images:
  - 'gcr.io/$PROJECT_ID/oauth-user-inspector:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/oauth-user-inspector:latest'
